version: 2.1
orbs:
    sonarcloud: sonarsource/sonarcloud@1.0.2
commands:
    pipenv-install-dev:
        steps:
            - run: python3 -m pip install pipenv
            - run: python3 -m pipenv install --dev
    pipenv-install:
        steps:
            - run: python3 -m pip install pipenv
            - run: python3 -m pipenv install
    python-lint:
        steps:
            - run: mkdir coverage && mkdir coverage/lint || exit 0
            - run: python3 -m pipenv run lint | python3 -m pipenv run pylint_report.py > ./coverage/lint/report.html || exit 0
            - store_artifacts:
                path: ./coverage/lint/report.html
    python-report:
        steps:
            - run: sudo rm -f /etc/boto.cfg
            - run: pipenv run coverage
            - store_test_results:
                path: ./coverage/reports
    pypi-setup:
        steps:
            - run: echo -e "[pypi]" >> ~/.pypirc
            - run: echo -e "username = __token__" >> ~/.pypirc
            - run: echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
    pypi-deploy:
        steps:
            - run: python3 -m pip install --user --upgrade setuptools wheel
            - run: python3 setup.py sdist bdist_wheel
            - run: python3 -m pip install --user --upgrade twine
            - run: python3 -m twine upload dist/*
jobs:
    install-build-test:
        docker:
            - image: cimg/python:3.8.6
            -
                image: postgis/postgis:12-2.5
                environment:
                    POSTGRES_USER: root
                    POSTGRES_PASSWORD: Lq4nKg&&TRhHv%7z
                    POSTGRES_DB: dbv-postgis
            -
                image: postgis/postgis:12-2.5
                command: -p 5433
                environment:
                    POSTGRES_USER: root
                    POSTGRES_PASSWORD: Lq4nKg&&TRhHv%7z
                    POSTGRES_DB: dbv-reset-postgis
        steps:
            - checkout
            - pipenv-install-dev
            - python-lint
            - python-report
            - sonarcloud/scan
    install-build-deploy:
        docker:
            - image: cimg/python:3.8.6
        steps:
            - checkout
            - pipenv-install
            - pypi-setup
            - pypi-deploy
workflows:
    install-build-deploy:
        jobs:
            - install-build-deploy:
                context:
                    - tools-cicd
                    - pypi-token
                    - sonarcloud-token
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
    install-build-test:
        jobs:
            - install-build-test:
                context:
                    - tools-cicd
                    - pypi-token
                    - sonarcloud-token
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        ignore: /dependabot.*/
